
// This file has been generated by the GUI designer. Do not modify.
namespace osiris
{
	public partial class gestion_cobranza
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox12;
		
		private global::Gtk.Button button_bloqueo_exp;
		
		private global::Gtk.HBox hbox23;
		
		private global::Gtk.Image image229;
		
		private global::Gtk.Label label30;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Entry entry_estatus;
		
		private global::Gtk.Label label22;
		
		private global::Gtk.Entry entry_numero_factura;
		
		private global::Gtk.HBox hbox14;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Entry entry_folio_servicio;
		
		private global::Gtk.Button button_selecatencion;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.Image image42;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.Entry entry_ingreso;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.Entry entry_egreso;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Entry entry_nro_pagare;
		
		private global::Gtk.Button button_selecpagare;
		
		private global::Gtk.HBox hbox11;
		
		private global::Gtk.Image image43;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Label label17;
		
		private global::Gtk.Entry entry_fecha_pagare;
		
		private global::Gtk.Label label18;
		
		private global::Gtk.Entry entry_fecha_vencpagare;
		
		private global::Gtk.Fixed fixed6;
		
		private global::Gtk.HBox hbox15;
		
		private global::Gtk.Label label19;
		
		private global::Gtk.Entry entry_monto_convenio;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Entry entry1;
		
		private global::Gtk.Label label20;
		
		private global::Gtk.Entry entry10;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Entry entry_pid_paciente;
		
		private global::Gtk.Entry entry_nombre_paciente;
		
		private global::Gtk.Button button_busca_paciente;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Image image41;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.HBox hbox17;
		
		private global::Gtk.Label label24;
		
		private global::Gtk.Entry entry_direccion_px;
		
		private global::Gtk.HBox hbox18;
		
		private global::Gtk.Label label25;
		
		private global::Gtk.Entry entry3;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.ScrolledWindow scrolledwindow2;
		
		private global::Gtk.TextView textview_motivo_ingreso;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.ComboBoxEntry comboboxentry_telefono;
		
		private global::Gtk.Label label23;
		
		private global::Gtk.Entry entry_tipo_paciente;
		
		private global::Gtk.Notebook notebook2;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.HBox hbox13;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.ScrolledWindow scrolledwindow4;
		
		private global::Gtk.TextView textview_notas;
		
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.TreeView treeview_gestion_cobranza;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Button button_guardanota;
		
		private global::Gtk.HBox hbox16;
		
		private global::Gtk.Image image44;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.Fixed fixed7;
		
		private global::Gtk.Button button_imprimir_gestcobrz;
		
		private global::Gtk.HBox hbox19;
		
		private global::Gtk.Image image45;
		
		private global::Gtk.Label label26;
		
		private global::Gtk.Button button_elimina_gestcobrz;
		
		private global::Gtk.HBox hbox21;
		
		private global::Gtk.Image image47;
		
		private global::Gtk.Label label28;
		
		private global::Gtk.Fixed fixed5;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.ScrolledWindow scrolledwindow3;
		
		private global::Gtk.TreeView treeview_servicios;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.Button button_impr_admisiones;
		
		private global::Gtk.HBox hbox20;
		
		private global::Gtk.Image image46;
		
		private global::Gtk.Label label27;
		
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Button button_abonar;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Image image227;
		
		private global::Gtk.Label label21;
		
		private global::Gtk.Button button1;
		
		private global::Gtk.Button button4;
		
		private global::Gtk.Button button5;
		
		private global::Gtk.Button button6;
		
		private global::Gtk.Button button8;
		
		private global::Gtk.Button button_export_movgest;
		
		private global::Gtk.HBox hbox22;
		
		private global::Gtk.Image image228;
		
		private global::Gtk.Label label29;
		
		private global::Gtk.Fixed fixed4;
		
		private global::Gtk.Button button_salir;
		
		private global::Gtk.Statusbar statusbar1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget osiris.gestion_cobranza
			this.Name = "osiris.gestion_cobranza";
			this.Title = global::Mono.Unix.Catalog.GetString ("Gestion de Cobranza");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child osiris.gestion_cobranza.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 3;
			// Container child hbox12.Gtk.Box+BoxChild
			this.button_bloqueo_exp = new global::Gtk.Button ();
			this.button_bloqueo_exp.CanFocus = true;
			this.button_bloqueo_exp.Name = "button_bloqueo_exp";
			// Container child button_bloqueo_exp.Gtk.Container+ContainerChild
			this.hbox23 = new global::Gtk.HBox ();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.image229 = new global::Gtk.Image ();
			this.image229.Name = "image229";
			this.image229.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_lock", global::Gtk.IconSize.Button);
			this.hbox23.Add (this.image229);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.image229]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.label30 = new global::Gtk.Label ();
			this.label30.Name = "label30";
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString ("Bloquear Exp");
			this.hbox23.Add (this.label30);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.label30]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.button_bloqueo_exp.Add (this.hbox23);
			this.hbox12.Add (this.button_bloqueo_exp);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.button_bloqueo_exp]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Estatus</small></b>");
			this.label1.UseMarkup = true;
			this.hbox12.Add (this.label1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.entry_estatus = new global::Gtk.Entry ();
			this.entry_estatus.CanFocus = true;
			this.entry_estatus.Name = "entry_estatus";
			this.entry_estatus.IsEditable = true;
			this.entry_estatus.InvisibleChar = '●';
			this.hbox12.Add (this.entry_estatus);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.entry_estatus]));
			w6.Position = 2;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Facturas</small></b>");
			this.label22.UseMarkup = true;
			this.hbox12.Add (this.label22);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label22]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.entry_numero_factura = new global::Gtk.Entry ();
			this.entry_numero_factura.CanFocus = true;
			this.entry_numero_factura.Name = "entry_numero_factura";
			this.entry_numero_factura.IsEditable = true;
			this.entry_numero_factura.InvisibleChar = '●';
			this.hbox12.Add (this.entry_numero_factura);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.entry_numero_factura]));
			w8.Position = 4;
			this.vbox2.Add (this.hbox12);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox12]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>N° Atencion</small></b>");
			this.label2.UseMarkup = true;
			this.hbox14.Add (this.label2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label2]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.entry_folio_servicio = new global::Gtk.Entry ();
			this.entry_folio_servicio.WidthRequest = 80;
			this.entry_folio_servicio.CanFocus = true;
			this.entry_folio_servicio.Name = "entry_folio_servicio";
			this.entry_folio_servicio.IsEditable = true;
			this.entry_folio_servicio.InvisibleChar = '●';
			this.hbox14.Add (this.entry_folio_servicio);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.entry_folio_servicio]));
			w11.Position = 1;
			// Container child hbox14.Gtk.Box+BoxChild
			this.button_selecatencion = new global::Gtk.Button ();
			this.button_selecatencion.CanFocus = true;
			this.button_selecatencion.Name = "button_selecatencion";
			// Container child button_selecatencion.Gtk.Container+ContainerChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.image42 = new global::Gtk.Image ();
			this.image42.Name = "image42";
			this.image42.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.hbox10.Add (this.image42);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.image42]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Selecion</small></b>");
			this.label12.UseMarkup = true;
			this.hbox10.Add (this.label12);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label12]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.button_selecatencion.Add (this.hbox10);
			this.hbox14.Add (this.button_selecatencion);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.button_selecatencion]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Fecha Atencion</small></b>");
			this.label15.UseMarkup = true;
			this.hbox14.Add (this.label15);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label15]));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.entry_ingreso = new global::Gtk.Entry ();
			this.entry_ingreso.CanFocus = true;
			this.entry_ingreso.Name = "entry_ingreso";
			this.entry_ingreso.IsEditable = false;
			this.entry_ingreso.InvisibleChar = '●';
			this.hbox14.Add (this.entry_ingreso);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.entry_ingreso]));
			w17.Position = 4;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Fecha Alta Med.</small></b>");
			this.label16.UseMarkup = true;
			this.hbox14.Add (this.label16);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label16]));
			w18.Position = 5;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.entry_egreso = new global::Gtk.Entry ();
			this.entry_egreso.CanFocus = true;
			this.entry_egreso.Name = "entry_egreso";
			this.entry_egreso.IsEditable = false;
			this.entry_egreso.InvisibleChar = '●';
			this.hbox14.Add (this.entry_egreso);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.entry_egreso]));
			w19.Position = 6;
			this.vbox2.Add (this.hbox14);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox14]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>N° Pagare</small></b>");
			this.label3.UseMarkup = true;
			this.hbox2.Add (this.label3);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label3]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entry_nro_pagare = new global::Gtk.Entry ();
			this.entry_nro_pagare.WidthRequest = 80;
			this.entry_nro_pagare.CanFocus = true;
			this.entry_nro_pagare.Name = "entry_nro_pagare";
			this.entry_nro_pagare.IsEditable = true;
			this.entry_nro_pagare.InvisibleChar = '●';
			this.hbox2.Add (this.entry_nro_pagare);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entry_nro_pagare]));
			w22.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button_selecpagare = new global::Gtk.Button ();
			this.button_selecpagare.CanFocus = true;
			this.button_selecpagare.Name = "button_selecpagare";
			// Container child button_selecpagare.Gtk.Container+ContainerChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.image43 = new global::Gtk.Image ();
			this.image43.Name = "image43";
			this.image43.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.hbox11.Add (this.image43);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.image43]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Selecion</small></b>");
			this.label13.UseMarkup = true;
			this.hbox11.Add (this.label13);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label13]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.button_selecpagare.Add (this.hbox11);
			this.hbox2.Add (this.button_selecpagare);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button_selecpagare]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Fecha Pagare</small></b>");
			this.label17.UseMarkup = true;
			this.hbox2.Add (this.label17);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label17]));
			w27.Position = 3;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entry_fecha_pagare = new global::Gtk.Entry ();
			this.entry_fecha_pagare.WidthRequest = 95;
			this.entry_fecha_pagare.CanFocus = true;
			this.entry_fecha_pagare.Name = "entry_fecha_pagare";
			this.entry_fecha_pagare.IsEditable = false;
			this.entry_fecha_pagare.InvisibleChar = '●';
			this.hbox2.Add (this.entry_fecha_pagare);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entry_fecha_pagare]));
			w28.Position = 4;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Fecha Vencimiento </small></b>");
			this.label18.UseMarkup = true;
			this.hbox2.Add (this.label18);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label18]));
			w29.Position = 5;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entry_fecha_vencpagare = new global::Gtk.Entry ();
			this.entry_fecha_vencpagare.WidthRequest = 95;
			this.entry_fecha_vencpagare.CanFocus = true;
			this.entry_fecha_vencpagare.Name = "entry_fecha_vencpagare";
			this.entry_fecha_vencpagare.IsEditable = false;
			this.entry_fecha_vencpagare.InvisibleChar = '●';
			this.hbox2.Add (this.entry_fecha_vencpagare);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entry_fecha_vencpagare]));
			w30.Position = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixed6 = new global::Gtk.Fixed ();
			this.fixed6.WidthRequest = 79;
			this.fixed6.Name = "fixed6";
			this.fixed6.HasWindow = false;
			this.hbox2.Add (this.fixed6);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixed6]));
			w31.Position = 7;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Monto Convenio</small></b>");
			this.label19.UseMarkup = true;
			this.hbox15.Add (this.label19);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label19]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.entry_monto_convenio = new global::Gtk.Entry ();
			this.entry_monto_convenio.CanFocus = true;
			this.entry_monto_convenio.Name = "entry_monto_convenio";
			this.entry_monto_convenio.IsEditable = false;
			this.entry_monto_convenio.InvisibleChar = '●';
			this.hbox15.Add (this.entry_monto_convenio);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.entry_monto_convenio]));
			w34.Position = 1;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Monto Cuota</small></b>");
			this.label4.UseMarkup = true;
			this.hbox15.Add (this.label4);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label4]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = false;
			this.entry1.InvisibleChar = '●';
			this.hbox15.Add (this.entry1);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.entry1]));
			w36.Position = 3;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Nro. de Cuotas</small></b>");
			this.label20.UseMarkup = true;
			this.hbox15.Add (this.label20);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label20]));
			w37.Position = 4;
			w37.Expand = false;
			w37.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.entry10 = new global::Gtk.Entry ();
			this.entry10.CanFocus = true;
			this.entry10.Name = "entry10";
			this.entry10.IsEditable = false;
			this.entry10.InvisibleChar = '●';
			this.hbox15.Add (this.entry10);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.entry10]));
			w38.Position = 5;
			this.vbox2.Add (this.hbox15);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox15]));
			w39.Position = 3;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Nombre </small></b>");
			this.label9.UseMarkup = true;
			this.hbox7.Add (this.label9);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label9]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.entry_pid_paciente = new global::Gtk.Entry ();
			this.entry_pid_paciente.WidthRequest = 6;
			this.entry_pid_paciente.CanFocus = true;
			this.entry_pid_paciente.Name = "entry_pid_paciente";
			this.entry_pid_paciente.Text = global::Mono.Unix.Catalog.GetString ("0");
			this.entry_pid_paciente.IsEditable = false;
			this.entry_pid_paciente.InvisibleChar = '●';
			this.hbox7.Add (this.entry_pid_paciente);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.entry_pid_paciente]));
			w41.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.entry_nombre_paciente = new global::Gtk.Entry ();
			this.entry_nombre_paciente.WidthRequest = 409;
			this.entry_nombre_paciente.CanFocus = true;
			this.entry_nombre_paciente.Name = "entry_nombre_paciente";
			this.entry_nombre_paciente.IsEditable = false;
			this.entry_nombre_paciente.InvisibleChar = '●';
			this.hbox7.Add (this.entry_nombre_paciente);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.entry_nombre_paciente]));
			w42.Position = 2;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button_busca_paciente = new global::Gtk.Button ();
			this.button_busca_paciente.CanFocus = true;
			this.button_busca_paciente.Name = "button_busca_paciente";
			// Container child button_busca_paciente.Gtk.Container+ContainerChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.image41 = new global::Gtk.Image ();
			this.image41.Name = "image41";
			this.image41.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Menu);
			this.hbox9.Add (this.image41);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.image41]));
			w43.Position = 0;
			w43.Expand = false;
			w43.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Buscar</small></b>");
			this.label11.UseMarkup = true;
			this.hbox9.Add (this.label11);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label11]));
			w44.Position = 1;
			w44.Expand = false;
			w44.Fill = false;
			this.button_busca_paciente.Add (this.hbox9);
			this.hbox7.Add (this.button_busca_paciente);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button_busca_paciente]));
			w46.Position = 3;
			w46.Expand = false;
			w46.Fill = false;
			this.vbox2.Add (this.hbox7);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox7]));
			w47.Position = 4;
			w47.Expand = false;
			w47.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox ();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.label24 = new global::Gtk.Label ();
			this.label24.WidthRequest = 60;
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Direccion</small></b>");
			this.label24.UseMarkup = true;
			this.hbox17.Add (this.label24);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.label24]));
			w48.Position = 0;
			w48.Expand = false;
			w48.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.entry_direccion_px = new global::Gtk.Entry ();
			this.entry_direccion_px.CanFocus = true;
			this.entry_direccion_px.Name = "entry_direccion_px";
			this.entry_direccion_px.IsEditable = false;
			this.entry_direccion_px.InvisibleChar = '●';
			this.hbox17.Add (this.entry_direccion_px);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.entry_direccion_px]));
			w49.Position = 1;
			this.vbox2.Add (this.hbox17);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox17]));
			w50.Position = 5;
			w50.Expand = false;
			w50.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox ();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label ();
			this.label25.WidthRequest = 60;
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Entre calles</small></b>");
			this.label25.UseMarkup = true;
			this.hbox18.Add (this.label25);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.label25]));
			w51.Position = 0;
			w51.Expand = false;
			w51.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.entry3 = new global::Gtk.Entry ();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = false;
			this.entry3.InvisibleChar = '●';
			this.hbox18.Add (this.entry3);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.entry3]));
			w52.Position = 1;
			this.vbox2.Add (this.hbox18);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox18]));
			w53.Position = 6;
			w53.Expand = false;
			w53.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Motivo de Ingreso </small></b>");
			this.label10.UseMarkup = true;
			this.hbox8.Add (this.label10);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label10]));
			w54.Position = 0;
			w54.Expand = false;
			w54.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.HeightRequest = 63;
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			this.textview_motivo_ingreso = new global::Gtk.TextView ();
			this.textview_motivo_ingreso.CanFocus = true;
			this.textview_motivo_ingreso.Name = "textview_motivo_ingreso";
			this.textview_motivo_ingreso.Editable = false;
			this.scrolledwindow2.Add (this.textview_motivo_ingreso);
			this.hbox8.Add (this.scrolledwindow2);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.scrolledwindow2]));
			w56.Position = 1;
			this.vbox2.Add (this.hbox8);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox8]));
			w57.Position = 7;
			w57.Expand = false;
			w57.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Telefono Marcado </small></b>");
			this.label7.UseMarkup = true;
			this.hbox5.Add (this.label7);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label7]));
			w58.Position = 0;
			w58.Expand = false;
			w58.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.comboboxentry_telefono = global::Gtk.ComboBoxEntry.NewText ();
			this.comboboxentry_telefono.Name = "comboboxentry_telefono";
			this.hbox5.Add (this.comboboxentry_telefono);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.comboboxentry_telefono]));
			w59.Position = 1;
			w59.Expand = false;
			w59.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Tipo de Paciente</small></b>");
			this.label23.UseMarkup = true;
			this.hbox5.Add (this.label23);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label23]));
			w60.Position = 2;
			w60.Expand = false;
			w60.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.entry_tipo_paciente = new global::Gtk.Entry ();
			this.entry_tipo_paciente.CanFocus = true;
			this.entry_tipo_paciente.Name = "entry_tipo_paciente";
			this.entry_tipo_paciente.IsEditable = true;
			this.entry_tipo_paciente.InvisibleChar = '●';
			this.hbox5.Add (this.entry_tipo_paciente);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.entry_tipo_paciente]));
			w61.Position = 3;
			this.vbox2.Add (this.hbox5);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
			w62.Position = 8;
			w62.Expand = false;
			w62.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.WidthRequest = 800;
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 0;
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Su Nota </small></b>");
			this.label5.UseMarkup = true;
			this.hbox13.Add (this.label5);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label5]));
			w63.Position = 0;
			w63.Expand = false;
			w63.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.scrolledwindow4 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow4.HeightRequest = 68;
			this.scrolledwindow4.CanFocus = true;
			this.scrolledwindow4.Name = "scrolledwindow4";
			this.scrolledwindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow4.Gtk.Container+ContainerChild
			this.textview_notas = new global::Gtk.TextView ();
			this.textview_notas.CanFocus = true;
			this.textview_notas.Name = "textview_notas";
			this.scrolledwindow4.Add (this.textview_notas);
			this.hbox13.Add (this.scrolledwindow4);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.scrolledwindow4]));
			w65.Position = 1;
			this.vbox5.Add (this.hbox13);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox13]));
			w66.Position = 0;
			w66.Expand = false;
			w66.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.HeightRequest = 195;
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.treeview_gestion_cobranza = new global::Gtk.TreeView ();
			this.treeview_gestion_cobranza.CanFocus = true;
			this.treeview_gestion_cobranza.Name = "treeview_gestion_cobranza";
			this.scrolledwindow1.Add (this.treeview_gestion_cobranza);
			this.vbox5.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.scrolledwindow1]));
			w68.Position = 1;
			this.hbox4.Add (this.vbox5);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox5]));
			w69.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			// Container child vbox4.Gtk.Box+BoxChild
			this.button_guardanota = new global::Gtk.Button ();
			this.button_guardanota.CanFocus = true;
			this.button_guardanota.Name = "button_guardanota";
			// Container child button_guardanota.Gtk.Container+ContainerChild
			this.hbox16 = new global::Gtk.HBox ();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.image44 = new global::Gtk.Image ();
			this.image44.Name = "image44";
			this.image44.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save", global::Gtk.IconSize.Menu);
			this.hbox16.Add (this.image44);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.image44]));
			w70.Position = 0;
			w70.Expand = false;
			w70.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Guardar</small></b>");
			this.label14.UseMarkup = true;
			this.hbox16.Add (this.label14);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.label14]));
			w71.Position = 1;
			w71.Expand = false;
			w71.Fill = false;
			this.button_guardanota.Add (this.hbox16);
			this.vbox4.Add (this.button_guardanota);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button_guardanota]));
			w73.Position = 0;
			w73.Expand = false;
			w73.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.fixed7 = new global::Gtk.Fixed ();
			this.fixed7.HeightRequest = 47;
			this.fixed7.Name = "fixed7";
			this.fixed7.HasWindow = false;
			this.vbox4.Add (this.fixed7);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.fixed7]));
			w74.Position = 1;
			w74.Expand = false;
			w74.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.button_imprimir_gestcobrz = new global::Gtk.Button ();
			this.button_imprimir_gestcobrz.CanFocus = true;
			this.button_imprimir_gestcobrz.Name = "button_imprimir_gestcobrz";
			// Container child button_imprimir_gestcobrz.Gtk.Container+ContainerChild
			this.hbox19 = new global::Gtk.HBox ();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.image45 = new global::Gtk.Image ();
			this.image45.Name = "image45";
			this.image45.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-print", global::Gtk.IconSize.Menu);
			this.hbox19.Add (this.image45);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.image45]));
			w75.Position = 0;
			w75.Expand = false;
			w75.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.label26 = new global::Gtk.Label ();
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Imprimir</small></b>");
			this.label26.UseMarkup = true;
			this.hbox19.Add (this.label26);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.label26]));
			w76.Position = 1;
			w76.Expand = false;
			w76.Fill = false;
			this.button_imprimir_gestcobrz.Add (this.hbox19);
			this.vbox4.Add (this.button_imprimir_gestcobrz);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button_imprimir_gestcobrz]));
			w78.Position = 2;
			w78.Expand = false;
			w78.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.button_elimina_gestcobrz = new global::Gtk.Button ();
			this.button_elimina_gestcobrz.CanFocus = true;
			this.button_elimina_gestcobrz.Name = "button_elimina_gestcobrz";
			// Container child button_elimina_gestcobrz.Gtk.Container+ContainerChild
			this.hbox21 = new global::Gtk.HBox ();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.image47 = new global::Gtk.Image ();
			this.image47.Name = "image47";
			this.image47.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			this.hbox21.Add (this.image47);
			global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.image47]));
			w79.Position = 0;
			w79.Expand = false;
			w79.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.label28 = new global::Gtk.Label ();
			this.label28.Name = "label28";
			this.label28.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Eliminar</small></b>");
			this.label28.UseMarkup = true;
			this.hbox21.Add (this.label28);
			global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.label28]));
			w80.Position = 1;
			w80.Expand = false;
			w80.Fill = false;
			this.button_elimina_gestcobrz.Add (this.hbox21);
			this.vbox4.Add (this.button_elimina_gestcobrz);
			global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button_elimina_gestcobrz]));
			w82.Position = 3;
			w82.Expand = false;
			w82.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.fixed5 = new global::Gtk.Fixed ();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			this.vbox4.Add (this.fixed5);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.fixed5]));
			w83.Position = 4;
			w83.Expand = false;
			w83.Fill = false;
			this.hbox4.Add (this.vbox4);
			global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox4]));
			w84.Position = 1;
			w84.Expand = false;
			w84.Fill = false;
			this.notebook2.Add (this.hbox4);
			// Notebook tab
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Movimientos</small></b>");
			this.label6.UseMarkup = true;
			this.notebook2.SetTabLabel (this.hbox4, this.label6);
			this.label6.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.scrolledwindow3 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow3.CanFocus = true;
			this.scrolledwindow3.Name = "scrolledwindow3";
			this.scrolledwindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow3.Gtk.Container+ContainerChild
			this.treeview_servicios = new global::Gtk.TreeView ();
			this.treeview_servicios.CanFocus = true;
			this.treeview_servicios.Name = "treeview_servicios";
			this.scrolledwindow3.Add (this.treeview_servicios);
			this.hbox3.Add (this.scrolledwindow3);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.scrolledwindow3]));
			w87.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.button_impr_admisiones = new global::Gtk.Button ();
			this.button_impr_admisiones.CanFocus = true;
			this.button_impr_admisiones.Name = "button_impr_admisiones";
			// Container child button_impr_admisiones.Gtk.Container+ContainerChild
			this.hbox20 = new global::Gtk.HBox ();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.image46 = new global::Gtk.Image ();
			this.image46.Name = "image46";
			this.image46.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-print", global::Gtk.IconSize.Menu);
			this.hbox20.Add (this.image46);
			global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.image46]));
			w88.Position = 0;
			w88.Expand = false;
			w88.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.label27 = new global::Gtk.Label ();
			this.label27.Name = "label27";
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Imprimir</small></b>");
			this.label27.UseMarkup = true;
			this.hbox20.Add (this.label27);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.label27]));
			w89.Position = 1;
			w89.Expand = false;
			w89.Fill = false;
			this.button_impr_admisiones.Add (this.hbox20);
			this.vbox6.Add (this.button_impr_admisiones);
			global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.button_impr_admisiones]));
			w91.Position = 0;
			w91.Expand = false;
			w91.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vbox6.Add (this.fixed1);
			global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.fixed1]));
			w92.Position = 1;
			w92.Expand = false;
			w92.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.vbox6.Add (this.fixed2);
			global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.fixed2]));
			w93.Position = 2;
			w93.Expand = false;
			w93.Fill = false;
			this.hbox3.Add (this.vbox6);
			global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox6]));
			w94.Position = 1;
			w94.Expand = false;
			w94.Fill = false;
			this.notebook2.Add (this.hbox3);
			global::Gtk.Notebook.NotebookChild w95 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.hbox3]));
			w95.Position = 1;
			// Notebook tab
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>His. Admisiones</small></b>");
			this.label8.UseMarkup = true;
			this.notebook2.SetTabLabel (this.hbox3, this.label8);
			this.label8.ShowAll ();
			this.vbox2.Add (this.notebook2);
			global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.notebook2]));
			w96.Position = 9;
			w96.Expand = false;
			w96.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w97.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			// Container child vbox3.Gtk.Box+BoxChild
			this.button_abonar = new global::Gtk.Button ();
			this.button_abonar.CanFocus = true;
			this.button_abonar.Name = "button_abonar";
			// Container child button_abonar.Gtk.Container+ContainerChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.image227 = new global::Gtk.Image ();
			this.image227.Name = "image227";
			this.image227.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.hbox6.Add (this.image227);
			global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.image227]));
			w98.Position = 0;
			w98.Expand = false;
			w98.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Pagos/Abon.</small></b>");
			this.label21.UseMarkup = true;
			this.hbox6.Add (this.label21);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label21]));
			w99.Position = 1;
			w99.Expand = false;
			w99.Fill = false;
			this.button_abonar.Add (this.hbox6);
			this.vbox3.Add (this.button_abonar);
			global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button_abonar]));
			w101.Position = 0;
			w101.Expand = false;
			w101.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Ref. Pers.");
			global::Gtk.Image w102 = new global::Gtk.Image ();
			w102.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-help", global::Gtk.IconSize.Menu);
			this.button1.Image = w102;
			this.vbox3.Add (this.button1);
			global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button1]));
			w103.Position = 1;
			w103.Expand = false;
			w103.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button ();
			this.button4.TooltipMarkup = "Haga Click aqui si quiere repartar la deuda";
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString ("Repactar");
			global::Gtk.Image w104 = new global::Gtk.Image ();
			w104.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.button4.Image = w104;
			this.vbox3.Add (this.button4);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button4]));
			w105.Position = 2;
			w105.Expand = false;
			w105.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString ("Juridico");
			global::Gtk.Image w106 = new global::Gtk.Image ();
			w106.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
			this.button5.Image = w106;
			this.vbox3.Add (this.button5);
			global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button5]));
			w107.Position = 3;
			w107.Expand = false;
			w107.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button6 = new global::Gtk.Button ();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Label = global::Mono.Unix.Catalog.GetString ("Incobrable");
			global::Gtk.Image w108 = new global::Gtk.Image ();
			w108.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
			this.button6.Image = w108;
			this.vbox3.Add (this.button6);
			global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button6]));
			w109.Position = 4;
			w109.Expand = false;
			w109.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button8 = new global::Gtk.Button ();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = global::Mono.Unix.Catalog.GetString ("Condonar");
			global::Gtk.Image w110 = new global::Gtk.Image ();
			w110.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			this.button8.Image = w110;
			this.vbox3.Add (this.button8);
			global::Gtk.Box.BoxChild w111 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button8]));
			w111.Position = 5;
			w111.Expand = false;
			w111.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button_export_movgest = new global::Gtk.Button ();
			this.button_export_movgest.CanFocus = true;
			this.button_export_movgest.Name = "button_export_movgest";
			// Container child button_export_movgest.Gtk.Container+ContainerChild
			this.hbox22 = new global::Gtk.HBox ();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.image228 = new global::Gtk.Image ();
			this.image228.Name = "image228";
			this.image228.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
			this.hbox22.Add (this.image228);
			global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.image228]));
			w112.Position = 0;
			w112.Expand = false;
			w112.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.label29 = new global::Gtk.Label ();
			this.label29.Name = "label29";
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><small>Movimientos</small></b>");
			this.label29.UseMarkup = true;
			this.hbox22.Add (this.label29);
			global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.label29]));
			w113.Position = 1;
			w113.Expand = false;
			w113.Fill = false;
			this.button_export_movgest.Add (this.hbox22);
			this.vbox3.Add (this.button_export_movgest);
			global::Gtk.Box.BoxChild w115 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button_export_movgest]));
			w115.Position = 6;
			w115.Expand = false;
			w115.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed ();
			this.fixed4.HeightRequest = 363;
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			this.vbox3.Add (this.fixed4);
			global::Gtk.Box.BoxChild w116 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed4]));
			w116.Position = 7;
			w116.Expand = false;
			w116.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button_salir = new global::Gtk.Button ();
			this.button_salir.CanFocus = true;
			this.button_salir.Name = "button_salir";
			this.button_salir.UseUnderline = true;
			this.button_salir.Label = global::Mono.Unix.Catalog.GetString ("Salir");
			global::Gtk.Image w117 = new global::Gtk.Image ();
			w117.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-quit", global::Gtk.IconSize.Menu);
			this.button_salir.Image = w117;
			this.vbox3.Add (this.button_salir);
			global::Gtk.Box.BoxChild w118 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button_salir]));
			w118.Position = 8;
			w118.Expand = false;
			w118.Fill = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w119.Position = 1;
			w119.Expand = false;
			w119.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w120.Position = 0;
			w120.Expand = false;
			w120.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.vbox1.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w121 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
			w121.Position = 1;
			w121.Expand = false;
			w121.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 898;
			this.DefaultHeight = 597;
			this.Show ();
			this.button_bloqueo_exp.Clicked += new global::System.EventHandler (this.on_button_bloqueo_exp_clicked);
			this.button_selecatencion.Clicked += new global::System.EventHandler (this.on_button_selecatencion_clicked);
			this.button_selecpagare.Clicked += new global::System.EventHandler (this.on_button_selecpagare_clicked);
			this.button_busca_paciente.Clicked += new global::System.EventHandler (this.on_button_busca_paciente_clicked);
			this.button_guardanota.Clicked += new global::System.EventHandler (this.on_button_guardanota_clicked);
			this.button_imprimir_gestcobrz.Clicked += new global::System.EventHandler (this.on_button_impr_mov_clicked);
			this.button_elimina_gestcobrz.Clicked += new global::System.EventHandler (this.on_button_elimina_gestcobrz_clicked);
			this.button_abonar.Clicked += new global::System.EventHandler (this.on_button_abonar_clicked);
			this.button_export_movgest.Clicked += new global::System.EventHandler (this.on_button_export_movgest_clicked);
			this.button_salir.Clicked += new global::System.EventHandler (this.on_cierraventanas_clicked);
		}
	}
}
