
// This file has been generated by the GUI designer. Do not modify.
namespace osiris
{
	public partial class credito_cobranza
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Button button_gestioncobranza;
		
		private global::Gtk.Button button1_pagofactura;
		
		private global::Gtk.Button button2;
		
		private global::Gtk.Button button_pagares_vigentes;
		
		private global::Gtk.Button button4;
		
		private global::Gtk.Button button_pagares_liquidados;
		
		private global::Gtk.Button button7;
		
		private global::Gtk.Button button6;
		
		private global::Gtk.Button button8;
		
		private global::Gtk.Button button9;
		
		private global::Gtk.Button button_reporte_abonos;
		
		private global::Gtk.Button button_exportar_pagares;
		
		private global::Gtk.Button button_venc_pagare;
		
		private global::Gtk.Button cierraventanas;
		
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Statusbar statusbar1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget osiris.credito_cobranza
			this.Name = "osiris.credito_cobranza";
			this.Title = global::Mono.Unix.Catalog.GetString ("Credito y Cobranza");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child osiris.credito_cobranza.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("\n<b><small>Credito y Cobranza</small></b>\n");
			this.label1.UseMarkup = true;
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.WidthRequest = 50;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fixed1]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.button_gestioncobranza = new global::Gtk.Button ();
			this.button_gestioncobranza.CanFocus = true;
			this.button_gestioncobranza.Name = "button_gestioncobranza";
			this.button_gestioncobranza.UseUnderline = true;
			this.button_gestioncobranza.Label = global::Mono.Unix.Catalog.GetString ("Gestion de Cobranza");
			this.vbox2.Add (this.button_gestioncobranza);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button_gestioncobranza]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button1_pagofactura = new global::Gtk.Button ();
			this.button1_pagofactura.CanFocus = true;
			this.button1_pagofactura.Name = "button1_pagofactura";
			this.button1_pagofactura.UseUnderline = true;
			this.button1_pagofactura.Label = global::Mono.Unix.Catalog.GetString ("Pago de Facturas");
			this.vbox2.Add (this.button1_pagofactura);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button1_pagofactura]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Convenios/Cuotas");
			this.vbox2.Add (this.button2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button2]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button_pagares_vigentes = new global::Gtk.Button ();
			this.button_pagares_vigentes.CanFocus = true;
			this.button_pagares_vigentes.Name = "button_pagares_vigentes";
			this.button_pagares_vigentes.UseUnderline = true;
			this.button_pagares_vigentes.Label = global::Mono.Unix.Catalog.GetString ("Pagares Vigentes");
			this.vbox2.Add (this.button_pagares_vigentes);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button_pagares_vigentes]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button ();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString ("Pagares Vencidos");
			this.vbox2.Add (this.button4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button4]));
			w7.Position = 4;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button_pagares_liquidados = new global::Gtk.Button ();
			this.button_pagares_liquidados.CanFocus = true;
			this.button_pagares_liquidados.Name = "button_pagares_liquidados";
			this.button_pagares_liquidados.UseUnderline = true;
			this.button_pagares_liquidados.Label = global::Mono.Unix.Catalog.GetString ("Pagares Liquidados");
			this.vbox2.Add (this.button_pagares_liquidados);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button_pagares_liquidados]));
			w8.Position = 5;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button ();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString ("Juridico");
			this.vbox2.Add (this.button7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button7]));
			w9.Position = 6;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button6 = new global::Gtk.Button ();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Label = global::Mono.Unix.Catalog.GetString ("Incobrable");
			this.vbox2.Add (this.button6);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button6]));
			w10.Position = 7;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button8 = new global::Gtk.Button ();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = global::Mono.Unix.Catalog.GetString ("Condonacion");
			this.vbox2.Add (this.button8);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button8]));
			w11.Position = 8;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button9 = new global::Gtk.Button ();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.Label = global::Mono.Unix.Catalog.GetString ("Repactacion");
			this.vbox2.Add (this.button9);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button9]));
			w12.Position = 9;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button_reporte_abonos = new global::Gtk.Button ();
			this.button_reporte_abonos.CanFocus = true;
			this.button_reporte_abonos.Name = "button_reporte_abonos";
			this.button_reporte_abonos.UseUnderline = true;
			this.button_reporte_abonos.Label = global::Mono.Unix.Catalog.GetString ("Mov. Abono/Pagos a Pagares");
			this.vbox2.Add (this.button_reporte_abonos);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button_reporte_abonos]));
			w13.Position = 10;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button_exportar_pagares = new global::Gtk.Button ();
			this.button_exportar_pagares.CanFocus = true;
			this.button_exportar_pagares.Name = "button_exportar_pagares";
			this.button_exportar_pagares.UseUnderline = true;
			this.button_exportar_pagares.Label = global::Mono.Unix.Catalog.GetString ("Mov. Pagares Generados");
			this.vbox2.Add (this.button_exportar_pagares);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button_exportar_pagares]));
			w14.Position = 11;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button_venc_pagare = new global::Gtk.Button ();
			this.button_venc_pagare.CanFocus = true;
			this.button_venc_pagare.Name = "button_venc_pagare";
			this.button_venc_pagare.UseUnderline = true;
			this.button_venc_pagare.Label = global::Mono.Unix.Catalog.GetString ("Mov. Vencimiento Pagares");
			this.vbox2.Add (this.button_venc_pagare);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button_venc_pagare]));
			w15.Position = 12;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.cierraventanas = new global::Gtk.Button ();
			this.cierraventanas.CanFocus = true;
			this.cierraventanas.Name = "cierraventanas";
			this.cierraventanas.UseUnderline = true;
			this.cierraventanas.Label = global::Mono.Unix.Catalog.GetString ("Salir");
			this.vbox2.Add (this.cierraventanas);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.cierraventanas]));
			w16.Position = 13;
			w16.Expand = false;
			w16.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.WidthRequest = 50;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox1.Add (this.fixed2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fixed2]));
			w18.Position = 2;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.vbox1.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 276;
			this.DefaultHeight = 441;
			this.Show ();
			this.button_gestioncobranza.Clicked += new global::System.EventHandler (this.on_gestioncobranza_clicked);
			this.button_pagares_vigentes.Clicked += new global::System.EventHandler (this.on_button_pagares_vigentes_clicked);
			this.button_pagares_liquidados.Clicked += new global::System.EventHandler (this.on_button_pagares_liquidados_clicked);
			this.button_reporte_abonos.Clicked += new global::System.EventHandler (this.on_button_reporte_abonos_clicked);
			this.button_exportar_pagares.Clicked += new global::System.EventHandler (this.on_button_exportar_pagares_clicked);
			this.button_venc_pagare.Clicked += new global::System.EventHandler (this.on_button_venc_pagare_clicked);
			this.cierraventanas.Clicked += new global::System.EventHandler (this.on_cierraventanas_clicked);
		}
	}
}
